options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  volumes:
    - name: docker-cache
      path: /kaniko/cache

steps:
  # Step 1: Build Docker image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - '--cache-from'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/first-step-images/first-step-frontend:latest'
      - '--tag'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/first-step-images/first-step-frontend:latest'
      - '.'
    volumes:
      - name: docker-cache
        path: /kaniko/cache

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/first-step-images/first-step-frontend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - first-step-frontend
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/first-step-images/first-step-frontend:latest
      - --region=europe-west1
      - --platform=managed
      - --port=3000
      - --allow-unauthenticated

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/first-step-images/first-step-frontend:latest'
