import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Dashboard | First Step",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <React.Fragment>{children}</React.Fragment>;
}
