import React from "react";
import type { Metadata } from "next";
import Header from "@/components/dashboard/Header";
import MainSidebar from "@/components/dashboard/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import SecondarySidebar from "@/components/dashboard/SecondarySidebar";

export const metadata: Metadata = {
  title: "Dashboard | First Step",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <MainSidebar />
      <main className="grow">
        <SidebarTrigger className="md:hidden" />
        <Header />
        <div className="px-4 md:px-10 py-10">{children}</div>
      </main>
      <div className="hidden xl:block">
        <SecondarySidebar />
      </div>
    </SidebarProvider>
  );
}
