import { Providers } from "@/app/providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | First Step",
    default: "First Step",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="py-10 lg:py-20">
      <Providers>{children}</Providers>
    </main>
  );
}
